---
name: CI

on:  # yamllint disable-line
  push:
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs:
  style:
    runs-on: ${{ matrix.os }}
    container:
      image: python:${{ matrix.python_version }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python_version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Check out the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Style
        run: |
          python -m pip install -U setuptools
          python -m pip install -e .[style]
          python setup.py style

  lint:
    runs-on: ${{ matrix.os }}
    container:
      image: python:${{ matrix.python_version }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python_version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Check out the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint
        run: |
          python -m pip install -U setuptools
          python -m pip install -e .[lint]
          yamllint .github .readthedocs.yaml
          python setup.py lint

  typing:
    runs-on: ${{ matrix.os }}
    container:
      image: python:${{ matrix.python_version }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python_version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Check out the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Typing
        run: |
          python -m pip install -U setuptools
          python -m pip install -e .[typing]
          python setup.py typing

  docs:
    runs-on: ${{ matrix.os }}
    container:
      image: python:${{ matrix.python_version }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python_version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Check out the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docs
        run: |
          python -m pip install -U setuptools
          python -m pip install -e .[docs]
          python setup.py docs

  test:
    runs-on: ${{ matrix.os }}
    container:
      image: python:${{ matrix.python_version }}
    name: "Test ${{ matrix.python_version }} | ${{ matrix.kivy_version }}"
    strategy:
      matrix:
        os:
          - ubuntu-latest
        kivy_version:
          - "2.3.1"
          - "2.3.0"
          - "2.2.1"
          - "2.2.0"
          - "2.1.0"
          - "2.0.0"
          - "1.11.1"
          - "1.11.0"

          # no manylinux wheels prior
          # - "1.10.1"
          # - "1.10.0"
          # and no 3.6 wheels prior

        python_version:
          # no f-strings prior
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        exclude:
          # no wheels
          # for 3.13
          - kivy_version: "2.3.0"
            python_version: "3.13"
          - kivy_version: "2.2.1"
            python_version: "3.13"
          - kivy_version: "2.2.0"
            python_version: "3.13"
          - kivy_version: "2.1.0"
            python_version: "3.13"
          - kivy_version: "2.0.0"
            python_version: "3.13"
          - kivy_version: "1.11.1"
            python_version: "3.13"
          - kivy_version: "1.11.0"
            python_version: "3.13"
          - kivy_version: "1.10.0"
            python_version: "3.13"

          # for 3.12
          - kivy_version: "2.2.1"
            python_version: "3.12"
          - kivy_version: "2.2.0"
            python_version: "3.12"
          - kivy_version: "2.1.0"
            python_version: "3.12"
          - kivy_version: "2.0.0"
            python_version: "3.12"
          - kivy_version: "1.11.1"
            python_version: "3.12"
          - kivy_version: "1.11.0"
            python_version: "3.12"
          - kivy_version: "1.10.0"
            python_version: "3.12"

          # for 3.11
          - kivy_version: "2.1.0"
            python_version: "3.11"
          - kivy_version: "2.0.0"
            python_version: "3.11"
          - kivy_version: "1.11.1"
            python_version: "3.11"
          - kivy_version: "1.11.0"
            python_version: "3.11"
          - kivy_version: "1.10.0"
            python_version: "3.11"

          # for 3.10
          - kivy_version: "2.0.0"
            python_version: "3.10"
          - kivy_version: "1.11.1"
            python_version: "3.10"
          - kivy_version: "1.11.0"
            python_version: "3.10"
          - kivy_version: "1.10.0"
            python_version: "3.10"

          # for 3.9
          - kivy_version: "2.0.0"
            python_version: "3.9"
          - kivy_version: "1.11.1"
            python_version: "3.9"
          - kivy_version: "1.11.0"
            python_version: "3.9"
          - kivy_version: "1.10.0"
            python_version: "3.9"

          # for 3.8
          - kivy_version: "2.0.0"
            python_version: "3.8"
          - kivy_version: "1.11.1"
            python_version: "3.8"
          - kivy_version: "1.11.0"
            python_version: "3.8"
          - kivy_version: "1.10.0"
            python_version: "3.8"

          # for 3.7
          - kivy_version: "2.3.1"
            python_version: "3.7"
          - kivy_version: "1.10.0"
            python_version: "3.7"

          # for 3.6
          - kivy_version: "2.3.1"
            python_version: "3.6"
          - kivy_version: "2.3.0"
            python_version: "3.6"
          - kivy_version: "2.2.1"
            python_version: "3.6"
          - kivy_version: "2.2.0"
            python_version: "3.6"
          - kivy_version: "2.1.0"
            python_version: "3.6"

    steps:
      - name: Check out the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          python -m pip install -U setuptools
          python -m pip install -U kivy==${{ matrix.kivy_version }}
          READTHEDOCS=1 python -m pip install -e .[test]
          python setup.py test
